obj-$(CONFIG_HIMA_HOTPLUG) += hima_hotplug.o
obj-$(CONFIG_CLUSTER_PLUG)	+= cluster_plug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
obj-$(CONFIG_MSM_HOTPLUG)       += msm_hotplug.o
obj-$(CONFIG_ASMP)		+= autosmp.o
obj-$(CONFIG_THUNDERPLUG_HOTPLUG) += thunderplug.o
obj-$(CONFIG_LAZYPLUG)			+= lazyplug.o
CFLAGS_lazyplug.o			+= -finline-functions
